services:
  - type: web
    name: bugprediction-api
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT
